// Simulated PartCatalogTopic fixture. A short sampler of stock parts
// spanning several categories so the dev-mode editor panel has
// something to render without a live KSP feed. Titles + descriptions
// are real-sounding to make scroll/search behaviour read true.

import type { PartCatalogData } from '../core/part-catalog-data';

export const SIM_PART_CATALOG: PartCatalogData = {
  entries: [
    {
      name: 'mk1pod',
      title: "Mk1 Command Pod",
      category: 'Pods',
      manufacturer: "Kerlington Model Rockets and Paper Products Inc.",
      cost: 600,
      mass: 0.84,
      description: "A basic command pod designed for one Kerbal.",
      techRequired: 'start',
      tags: 'capsule crew cmd mk1',
      iconBase64: '',
    },
    {
      name: 'Mark1-2Pod',
      title: "Mk1-3 Command Pod",
      category: 'Pods',
      manufacturer: "Kerlington Model Rockets and Paper Products Inc.",
      cost: 3800,
      mass: 2.72,
      description: "Holds three Kerbals in relative comfort.",
      techRequired: 'advRocketry',
      tags: 'capsule crew cmd mk1-3',
      iconBase64: '',
    },
    {
      name: 'probeCoreOcto',
      title: "Probodobodyne OKTO",
      category: 'Pods',
      manufacturer: "Probodobodyne Inc.",
      cost: 450,
      mass: 0.1,
      description: 'A tiny probe core for early unmanned missions.',
      techRequired: 'flightControl',
      tags: 'probe unmanned octo',
      iconBase64: '',
    },
    {
      name: 'liquidEngine',
      title: "LV-T45 'Swivel' Liquid Fuel Engine",
      category: 'Engine',
      manufacturer: 'Jebediah Kerman\'s Junkyard and Spaceship Parts Co.',
      cost: 1200,
      mass: 1.5,
      description: 'A reliable gimballed liquid fuel engine.',
      techRequired: 'generalRocketry',
      tags: 'engine swivel lv-t45',
      iconBase64: '',
    },
    {
      name: 'liquidEngine2',
      title: "LV-T30 'Reliant' Liquid Fuel Engine",
      category: 'Engine',
      manufacturer: 'Jebediah Kerman\'s Junkyard and Spaceship Parts Co.',
      cost: 1100,
      mass: 1.25,
      description: 'A non-gimballed workhorse with better ISP than the Swivel.',
      techRequired: 'basicRocketry',
      tags: 'engine reliant lv-t30',
      iconBase64: '',
    },
    {
      name: 'solidBooster',
      title: "RT-10 'Hammer' Solid Fuel Booster",
      category: 'Engine',
      manufacturer: "Kerlington Model Rockets and Paper Products Inc.",
      cost: 400,
      mass: 3.56,
      description: 'A burn-once solid fuel booster. Cheap thrust.',
      techRequired: 'start',
      tags: 'srb booster hammer rt-10',
      iconBase64: '',
    },
    {
      name: 'fuelTank',
      title: "FL-T800 Fuel Tank",
      category: 'FuelTank',
      manufacturer: 'Jebediah Kerman\'s Junkyard and Spaceship Parts Co.',
      cost: 800,
      mass: 4.5,
      description: 'Stocks 360 units of liquid fuel and 440 of oxidizer.',
      techRequired: 'basicRocketry',
      tags: 'fuel tank lfo',
      iconBase64: '',
    },
    {
      name: 'fuelTank1-2',
      title: "FL-T400 Fuel Tank",
      category: 'FuelTank',
      manufacturer: 'Jebediah Kerman\'s Junkyard and Spaceship Parts Co.',
      cost: 500,
      mass: 2.25,
      description: 'Holds half as much as the FL-T800 at half the mass.',
      techRequired: 'basicRocketry',
      tags: 'fuel tank lfo',
      iconBase64: '',
    },
    {
      name: 'stackDecoupler',
      title: "TR-18A Stack Decoupler",
      category: 'Coupling',
      manufacturer: 'Kerbodyne',
      cost: 400,
      mass: 0.05,
      description: 'Separates stages. Gives 250 kN of ejection force.',
      techRequired: 'engineering101',
      tags: 'decoupler stack separator',
      iconBase64: '',
    },
    {
      name: 'parachuteSingle',
      title: "Mk16 Parachute",
      category: 'Utility',
      manufacturer: "Kerlington Model Rockets and Paper Products Inc.",
      cost: 422,
      mass: 0.1,
      description: 'A basic radial parachute for graceful descents.',
      techRequired: 'start',
      tags: 'chute parachute recovery',
      iconBase64: '',
    },
    {
      name: 'longAntenna',
      title: "Communotron 16",
      category: 'Communication',
      manufacturer: 'Ionic Symphonic Protonic Electronics',
      cost: 300,
      mass: 0.005,
      description: 'A small, deployable direct antenna.',
      techRequired: 'basicScience',
      tags: 'antenna comm direct',
      iconBase64: '',
    },
    {
      name: 'solarPanels1',
      title: "OX-STAT Photovoltaic Panels",
      category: 'Electrical',
      manufacturer: 'Ionic Symphonic Protonic Electronics',
      cost: 75,
      mass: 0.005,
      description: 'Cheap surface-mount solar panels.',
      techRequired: 'basicScience',
      tags: 'solar panel electric',
      iconBase64: '',
    },
    {
      name: 'batteryBank',
      title: "Z-400 Rechargeable Battery",
      category: 'Electrical',
      manufacturer: 'Zaltonic Electronics',
      cost: 550,
      mass: 0.02,
      description: 'A 400-unit rechargeable battery pack.',
      techRequired: 'basicScience',
      tags: 'battery ec electric z-400',
      iconBase64: '',
    },
    {
      name: 'sensorBarometer',
      title: "PresMat Barometer",
      category: 'Science',
      manufacturer: 'Probodobodyne Inc.',
      cost: 3300,
      mass: 0.005,
      description: 'Measures atmospheric pressure.',
      techRequired: 'basicScience',
      tags: 'science pressure',
      iconBase64: '',
    },
    {
      name: 'sensorThermometer',
      title: "2HOT Thermometer",
      category: 'Science',
      manufacturer: 'Probodobodyne Inc.',
      cost: 900,
      mass: 0.005,
      description: 'Measures ambient temperature.',
      techRequired: 'basicScience',
      tags: 'science temp',
      iconBase64: '',
    },
    {
      name: 'winglet3',
      title: "AV-R8 Winglet",
      category: 'Aero',
      manufacturer: 'C7 Aerospace Division',
      cost: 640,
      mass: 0.08,
      description: 'Small aerodynamic control surface.',
      techRequired: 'aerodynamicSystems',
      tags: 'winglet control surface av-r8',
      iconBase64: '',
    },
    {
      name: 'strutConnector',
      title: "EAS-4 Strut Connector",
      category: 'Structural',
      manufacturer: 'Experimental Engineering Group',
      cost: 42,
      mass: 0.05,
      description: 'Rigid strut for reinforcing wobbly builds.',
      techRequired: 'generalConstruction',
      tags: 'strut structural',
      iconBase64: '',
    },
  ],
};
